<a href="https://colab.research.google.com/github/Alecia113/python_-basic_practice/blob/numpy/_directed_exercises_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **向量和矩阵；numpy**

In [12]:
import numpy as np
vector = np.array([1,2,3,4])
metrix = np.array([[1,2,3],[4,5,6]])
print(vector)
print(metrix)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [ ]:
vector.shape


In [9]:
metrix

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
metrix.shape

(2, 3)

**numpy.arange()**定义等距向量或矩阵

In [18]:
import numpy as np
a = np.arange(15) #rn 单词要打对啊
b = np.arange(10,30,5) #开始结尾和间距

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
b

array([10, 15, 20, 25])

In [20]:
c = np.arange(15).reshape(3,5)#三行五列.reshape

In [21]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
print(a)
print(b)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[10 15 20 25]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


**np.zeros** 定义的数据玩味0的向量或矩阵

In [23]:
d = np.zeros(3)

In [25]:
d

array([0., 0., 0.])

In [26]:
d1 = np.zeros(3, dtype=np.int32)

In [27]:
d1

array([0, 0, 0], dtype=int32)

In [29]:
d2 = np.zeros(3, dtype=np.int32, )

In [30]:
d2

array([0, 0, 0], dtype=int32)

In [32]:
d3 = np.zeros((3))

In [33]:
d3

array([0., 0., 0.])

In [34]:
d4 = np.zeros((2,3)) #行列式

In [36]:
d4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [38]:
print(d1)
print(d2)
print(d3)
print(d4)

[0 0 0]
[0 0 0]
[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


**np.ones()** 可以定义全为1

In [40]:
import numpy as np
e1 = np.ones(3, dtype=np.int32,)

In [41]:
e1

array([1, 1, 1], dtype=int32)

In [43]:
e2 = np.ones(5, dtype=np.int32,)

In [44]:
e2

array([1, 1, 1, 1, 1], dtype=int32)

In [45]:
e3 = np.ones((2,3))

In [46]:
e3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
e4 = np.ones((4,6))

In [48]:
e4

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [49]:
print(e1)
print(e2)
print(e3)
print(e4)

[1 1 1]
[1 1 1 1 1]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


**numpy.random.random()**

In [53]:
import numpy as np
f1 = np.random.random(3)

In [56]:
f1

array([0.38794224, 0.94055668, 0.83196526])

In [66]:
f2 = 10 * np.random.random(3)

In [67]:
f2

array([7.44710529, 0.44640817, 8.48819462])

In [73]:
f3 = np.random.random((3,2))

In [74]:
f3

array([[0.94191655, 0.1047416 ],
       [0.60753055, 0.94301683],
       [0.38152906, 0.61565525]])

In [75]:
f4 = 10 * np.random.random((3,2))

In [77]:
f4

array([[6.29052432, 8.77617883],
       [0.13056445, 2.45196533],
       [9.41775176, 7.137024  ]])

**numpy.linspace()**  由区间中固定等距元素组成1的向量或矩阵

In [81]:
import numpy as np
g1 = np.linspace(0, 2*np.pi, 6)

In [86]:
g1 

array([0.        , 1.25663706, 2.51327412, 3.76991118, 5.02654825,
       6.28318531])

In [84]:
g2 = g1.reshape(2,3)

In [85]:
g2

array([[0.        , 1.25663706, 2.51327412],
       [3.76991118, 5.02654825, 6.28318531]])

In [87]:
g3 = np.linspace(10, 30)
#np.linspace(start（必有）, stop（有时有）, num=50（均分数量）, endpoint=True（包含stop就True，不包含就False）, retstep=False（如果为True，返回值和步长）, dtype=None（参数类型，不定义的话根据前面参数的数据类型）, axis=0)

In [88]:
g3  #abbr. 线性等分向量（linear space）linsapce

array([10.        , 10.40816327, 10.81632653, 11.2244898 , 11.63265306,
       12.04081633, 12.44897959, 12.85714286, 13.26530612, 13.67346939,
       14.08163265, 14.48979592, 14.89795918, 15.30612245, 15.71428571,
       16.12244898, 16.53061224, 16.93877551, 17.34693878, 17.75510204,
       18.16326531, 18.57142857, 18.97959184, 19.3877551 , 19.79591837,
       20.20408163, 20.6122449 , 21.02040816, 21.42857143, 21.83673469,
       22.24489796, 22.65306122, 23.06122449, 23.46938776, 23.87755102,
       24.28571429, 24.69387755, 25.10204082, 25.51020408, 25.91836735,
       26.32653061, 26.73469388, 27.14285714, 27.55102041, 27.95918367,
       28.36734694, 28.7755102 , 29.18367347, 29.59183673, 30.        ])

In [94]:
g4 = np.linspace(10, 30 , num=100, retstep=1, ) #别忘了每个属性中间用，隔开。

In [97]:
g4

(array([10.        , 10.2020202 , 10.4040404 , 10.60606061, 10.80808081,
        11.01010101, 11.21212121, 11.41414141, 11.61616162, 11.81818182,
        12.02020202, 12.22222222, 12.42424242, 12.62626263, 12.82828283,
        13.03030303, 13.23232323, 13.43434343, 13.63636364, 13.83838384,
        14.04040404, 14.24242424, 14.44444444, 14.64646465, 14.84848485,
        15.05050505, 15.25252525, 15.45454545, 15.65656566, 15.85858586,
        16.06060606, 16.26262626, 16.46464646, 16.66666667, 16.86868687,
        17.07070707, 17.27272727, 17.47474747, 17.67676768, 17.87878788,
        18.08080808, 18.28282828, 18.48484848, 18.68686869, 18.88888889,
        19.09090909, 19.29292929, 19.49494949, 19.6969697 , 19.8989899 ,
        20.1010101 , 20.3030303 , 20.50505051, 20.70707071, 20.90909091,
        21.11111111, 21.31313131, 21.51515152, 21.71717172, 21.91919192,
        22.12121212, 22.32323232, 22.52525253, 22.72727273, 22.92929293,
        23.13131313, 23.33333333, 23.53535354, 23.7

**np.logspace**返回等比数列

In [ ]:
#https://blog.csdn.net/duanlianvip/article/details/100102797?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522161490309916780255225143%2522%252C%2522scm%2522%253A%252220140713.130102334.pc%255Fall.%2522%257D&request_id=161490309916780255225143&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~first_rank_v2~rank_v29-2-100102797.first_rank_v2_pc_rank_v29&utm_term=.linspace参数含义
'这个人讲的参数用法都很详细