<a href="https://colab.research.google.com/github/Alecia113/python_-basic_practice/blob/numpy/_directed_exercises_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# **向量和矩阵；numpy**

In [12]:
import numpy as np
vector = np.array([1,2,3,4])
metrix = np.array([[1,2,3],[4,5,6]])
print(vector)
print(metrix)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [ ]:
vector.shape


In [9]:
metrix

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
metrix.shape

(2, 3)

**numpy.arange()**定义等距向量或矩阵

In [18]:
import numpy as np
a = np.arange(15) #rn 单词要打对啊
b = np.arange(10,30,5) #开始结尾和间距

In [17]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [19]:
b

array([10, 15, 20, 25])